app:
  name: MS UserVo Service
  description: REST API for create users using JWT.
  version: 0.0.1
  contact:
    name: Marco A Montilla R
    email: marcomarco@marcomarco.blog
    url: http://marcomarco.blog

  jwt:
    generator:
      key: secret-jwt

  user:
    validations:
      regexp:
        password: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,16}$
        message: "El formato del password debe tener entre 8 y 16 digitos, de los cuales al menos un numero, una minusculas y caracter especial"

server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:mem:registry
    username: sa
    password: marcomarco
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  mvc:
    throw-exception-if-no-handler-found: true

