app:
  name: MS UserVo Service
  description: REST API for create users using JWT.
  version: 0.0.1
  contact:
    name: Marco A Montilla R
    email: marcomarco@marcomarco.blog
    url: http://marcomarco.blog

  user:
    validations:
      regexp:
        password: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W)(?!.* ).{8,16}$

server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:mem:registry
    username: sa
    password: marcomarco
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  mvc:
    throw-exception-if-no-handler-found: true

