app:
  name: MS User Service
  description: REST API for create users using JWT.
  version: 0.0.1
  contact:
    name: Marco A Montilla R
    email: marcomarco@marcomarco.blog
    url: http://marcomarco.blog

server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:h2:mem:conference
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

